bundle:
  groupId: "io.jenkins-x"
  artifactId: "jenkins-x-serverless"
  vendor: "Jenkins X project"
  title: "Jenkins X Serverless images"
  description: "Jenkins X Serverless build images, produced by Custom WAR Packager"
buildSettings:
  pom: pom.xml
  pomIgnoreRoot: false
  jenkinsfileRunner:
    source:
      groupId: "io.jenkins"
      artifactId: "jenkinsfile-runner"
      build:
        noCache: true
      source:
        git: https://github.com/jenkinsci/jenkinsfile-runner.git
        commit: e60d694f6f712160603fb7fc127e3b3caefd4d16
    docker:
      base: "jenkins/jenkins:2.150.2"
      tag: "jenkins-experimental/cwp-jenkinsfile-runner-demo"
      build: false
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: "2.150.2"
casc:
  - id: "casc"
    source:
      dir: casc.yml
